TARGET1=led.out
TARGET1_MAIN=main.c
TEST_TARGET=tests.out

TESTS_DIR=./test
SOURCES_DIR=./src
INCLUDE_DIR=./include
UNITYC_DIR=./unityc
UNITYC_SOURCES_DIR=$(UNITYC_DIR)/src
UNITYC_INCLUDE_DIR=$(UNITYC_DIR)/include
OUTPUT_DIR=./output

OBJS=$(wildcard $(SOURCES_DIR)/*)
OUT_OBJS=$(addprefix $(OUTPUT_DIR)/,$(OBJS))
TEST_OBJS=$(wildcard $(TESTS_DIR)/*)
OUT_TEST_OBJS=$(addprefix $(OUTPUT_DIR)/,$(TEST_OBJS))
UNITYC_OBJS=$(wildcard $(UNITYC_SOURCES_DIR)/*)
OUT_UNITYC_OBJS=$(addprefix $(OUTPUT_DIR)/,$(UNITYC_OBJS))

$(OUTPUT_DIR)/%.o : $(SOURCES_DIR)/%.c $(TESTS_DIR)/%.c $(UNITYC_SOURCES_DIR)/%.c
	$(CC) -c $< -I$(INCLUDE_DIR) -o $@

all: $(TEST_TARGET) $(TARGET1)

$(TEST_TARGET): $(OBJS) $(TEST_OBJS) $(UNITYC_OBJS)
	$(CC) $? -I$(INCLUDE_DIR) -I$(UNITYC_INCLUDE_DIR) -o $(OUTPUT_DIR)/$(TEST_TARGET)
	exec $(OUTPUT_DIR)/$(TEST_TARGET)

$(TARGET1): $(OBJS)
	$(CC) $(TARGET1_MAIN) $? -I$(INCLUDE_DIR) -o $(OUTPUT_DIR)/$(TARGET1)

clean:
	rm -rf $(OUTPUT_DIR)/*.o $(OUTPUT_DIR)/$(TARGET1) $(OUTPUT_DIR)/$(TEST_TARGET)
